inherit_from: .rubocop_todo.yml

# In some cases we just need to catch an exception, rather than
# actually handle it. Allow the tests to make use of this shortcut.
Lint/SuppressedException:
  AllowComments: true
  Exclude:
    - 'test/**/*.rb'

# Allow this "useless" test, as we are testing <=> here.
Lint/UselessComparison:
  Exclude:
    - 'test/entry_test.rb'
