inherit_from: .rubocop_todo.yml

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# In some cases we just need to catch an exception, rather than
# actually handle it. Allow the tests to make use of this shortcut.
Lint/SuppressedException:
  AllowComments: true
  Exclude:
    - 'test/**/*.rb'

# Allow this "useless" test, as we are testing <=> here.
Lint/UselessComparison:
  Exclude:
    - 'test/entry_test.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

# Turn this cop off for these files as it fires for objects without
# an empty? method.
Style/ZeroLengthPredicate:
  Exclude:
    - 'lib/zip/file.rb'
    - 'lib/zip/input_stream.rb'
