language: ruby
env:
  global:
    - JAVA_OPTS="-X+O"
jdk:
  - oraclejdk7
  - openjdk7
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
  - jruby-19mode
before_install:
  - gem update --system
  - gem --version
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zip unzip
  - echo $PATH
branches:
  only:
    - master
allow_failures:
  - rvm: ruby-head
