language: ruby
sudo: false
cache: bundler
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
matrix:
  include:
  - rvm: jruby
    jdk: oraclejdk8
  - rvm: jruby
    jdk: openjdk7
  - rvm: jruby-head
    jdk: oraclejdk8
  - rvm: rbx-3
    env:
      - RUBYOPT="-rbundler/deprecate"
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
    - rvm: jruby-head
before_install:
  - "if $(ruby -e 'exit(RUBY_VERSION >= \"2.3.0\")'); then gem update --system; fi"
  - "if $(ruby -e 'exit(RUBY_VERSION <  \"2.3.0\")'); then gem update --system 2.7.8; fi"
  - "if $(ruby -e 'exit(RUBY_VERSION >= \"2.3.0\")'); then gem install bundler; fi"
  - "if $(ruby -e 'exit(RUBY_VERSION <  \"2.3.0\")'); then gem install bundler --version 1.17.3; fi"
  - gem --version
before_script:
  - echo `whereis zip`
  - echo `whereis unzip`
env:
  global:
    - JRUBY_OPTS="--debug"
    - COVERALLS_PARALLEL=true
notifications:
  webhooks: https://coveralls.io/webhook
